extends:
  - plugin:@typescript-eslint/recommended
plugins: ['@typescript-eslint']
parser: '@typescript-eslint/parser'
rules:
  indent: [error, 4]
  quotes: [error, single]
  semi: off
  '@typescript-eslint/semi': [error, never]